version: '3.8'

services:
  # 1. 데이터베이스
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tft
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. 백엔드 (NestJS)
  backend:
    build:
      context: ./backend/tft  # 경로를 한 단계 더 깊게 수정했습니다.
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "mysql://root:1234@db:3306/tft"
    depends_on:
      - db

  # 3. 프론트엔드 (NextJS)
  frontend:
    build:
      context: ./frontend/tft  # 경로를 한 단계 더 깊게 수정했습니다.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data: