-- AlterTable
ALTER TABLE `homework` MODIFY `status` ENUM('ASSIGNED', 'COMPLETE', 'CARRIED_OVER', 'CANCELED') NOT NULL DEFAULT 'ASSIGNED';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `deletedAt` DATETIME(3) NULL;
